function collectStorage(data) {
  data.bgmSrc = storage.bgms.items.default.src;
  data.powerupMagnetSrc = storage.powerupMagnet.items.powerupMagnet.src;
  data.powerupReverseSrc = storage.powerupReverse.items.powerupReverse.src;
  data.powerupTimeSrc = storage.powerupTime.items.powerupTime.src;
  data.powerupTornadoSrc = storage.powerupTornado.items.powerupTornado.src;
  data.barbieBoatSrc = storage.barbieBoat.items.barbieBoat.src;
  data.barbieCarSrc = storage.barbieCar.items.barbieCar.src;
  data.barbieGirl1Src = storage.barbieGirl1.items.barbieGirl1.src;
  data.barbieGirl2Src = storage.barbieGirl2.items.barbieGirl2.src;
  data.barbieHouseSrc = storage.barbieHouse.items.barbieHouse.src;
  data.barbieKenSrc = storage.barbieKen.items.barbieKen.src;
  data.handSrc = storage.hand.items.hand.src;
  data.endcardLogoSrc = storage.endcardLogo.items.endcardLogo.src;
  data.endcardButtonSrc = storage.endcardButton.items.endcardButton.src;
  data.powerupMagnetGraySrc =
    storage.powerupMagnetGray.items.powerupMagnetGray.src;
  data.powerupReverseGraySrc =
    storage.powerupReverseGray.items.powerupReverseGray.src;
  data.powerupTimeGraySrc = storage.powerupTimeGray.items.powerupTimeGray.src;
  data.powerupTornadoGraySrc =
    storage.powerupTornadoGray.items.powerupTornadoGray.src;
  data.middleImageSrc = storage.middleImage.items.middleImage.src;
  data.collectSrc = storage.collect.items.collect.src;
  data.addTraySrc = storage.addTray.items.addTray.src;
  data.clickSrc = storage.click.items.click.src;
  data.matchSrc = storage.match.items.match.src;
  data.reverseSrc = storage.reverse.items.reverse.src;
  data.magnetSrc = storage.magnet.items.magnet.src;
  data.tornadoSrc = storage.tornado.items.tornado.src;
  data.timeSrc = storage.time.items.time.src;
  data.nextLevelSrc = storage.nextLevel.items.nextLevel.src;
  data.barbieBoatRemainingSrc =
    storage.barbieBoatRemaining.items.barbieBoatRemaining.src;
  data.barbieCarRemainingSrc =
    storage.barbieCarRemaining.items.barbieCarRemaining.src;
  data.barbieGirl1RemainingSrc =
    storage.barbieGirl1Remaining.items.barbieGirl1Remaining.src;
  data.barbieGirl2RemainingSrc =
    storage.barbieGirl2Remaining.items.barbieGirl2Remaining.src;
  data.barbieHouseRemainingSrc =
    storage.barbieHouseRemaining.items.barbieHouseRemaining.src;
  data.barbieKenRemainingSrc =
    storage.barbieKenRemaining.items.barbieKenRemaining.src;
}

const storage = {
  barbieBoatRemaining: {
    label: 'Barbie Boat Remaining',
    description: 'Uploaded Barbie Boat Remaining for the game.',
    aiDescription: 'a collection of Barbie Boat Remaining for branding',
    items: {
      barbieBoatRemaining: {
        label: 'Barbie Boat Remaining',
        description: 'The Barbie Boat Remaining for the game.',
        aiDescription: 'Barbie Boat Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieBoatRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieCarRemaining: {
        label: 'Barbie Car Remaining',
        description: 'The Barbie Car Remaining for the game.',
        aiDescription: 'Barbie Car Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieCarRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1Remaining: {
        label: 'Barbie Girl 1 Remaining',
        description: 'The Barbie Girl 1 Remaining for the game.',
        aiDescription: 'Barbie Girl 1 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl1Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2Remaining: {
        label: 'Barbie Girl 2 Remaining',
        description: 'The Barbie Girl 2 Remaining for the game.',
        aiDescription: 'Barbie Girl 2 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl2Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouseRemaining: {
        label: 'Barbie House Remaining',
        description: 'The Barbie House Remaining for the game.',
        aiDescription: 'Barbie House Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieHouseRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieKenRemaining: {
        label: 'Barbie Ken Remaining',
        description: 'The Barbie Ken Remaining for the game.',
        aiDescription: 'Barbie Ken Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieKenRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieCarRemaining: {
    label: 'Barbie Car Remaining',
    description: 'Uploaded Barbie Car Remaining for the game.',
    aiDescription: 'a collection of Barbie Car Remaining for branding',
    items: {
      barbieCarRemaining: {
        label: 'Barbie Car Remaining',
        description: 'The Barbie Car Remaining for the game.',
        aiDescription: 'Barbie Car Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieCarRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoatRemaining: {
        label: 'Barbie Boat Remaining',
        description: 'The Barbie Boat Remaining for the game.',
        aiDescription: 'Barbie Boat Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieBoatRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1Remaining: {
        label: 'Barbie Girl 1 Remaining',
        description: 'The Barbie Girl 1 Remaining for the game.',
        aiDescription: 'Barbie Girl 1 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl1Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2Remaining: {
        label: 'Barbie Girl 2 Remaining',
        description: 'The Barbie Girl 2 Remaining for the game.',
        aiDescription: 'Barbie Girl 2 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl2Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouseRemaining: {
        label: 'Barbie House Remaining',
        description: 'The Barbie House Remaining for the game.',
        aiDescription: 'Barbie House Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieHouseRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieKenRemaining: {
        label: 'Barbie Ken Remaining',
        description: 'The Barbie Ken Remaining for the game.',
        aiDescription: 'Barbie Ken Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieKenRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieGirl1Remaining: {
    label: 'Barbie Girl 1 Remaining',
    description: 'Uploaded Barbie Girl 1 Remaining for the game.',
    aiDescription: 'a collection of Barbie Girl 1 Remaining for branding',
    items: {
      barbieGirl1Remaining: {
        label: 'Barbie Girl 1 Remaining',
        description: 'The Barbie Girl 1 Remaining for the game.',
        aiDescription: 'Barbie Girl 1 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl1Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoatRemaining: {
        label: 'Barbie Boat Remaining',
        description: 'The Barbie Boat Remaining for the game.',
        aiDescription: 'Barbie Boat Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieBoatRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieCarRemaining: {
        label: 'Barbie Car Remaining',
        description: 'The Barbie Car Remaining for the game.',
        aiDescription: 'Barbie Car Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieCarRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2Remaining: {
        label: 'Barbie Girl 2 Remaining',
        description: 'The Barbie Girl 2 Remaining for the game.',
        aiDescription: 'Barbie Girl 2 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl2Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouseRemaining: {
        label: 'Barbie House Remaining',
        description: 'The Barbie House Remaining for the game.',
        aiDescription: 'Barbie House Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieHouseRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieKenRemaining: {
        label: 'Barbie Ken Remaining',
        description: 'The Barbie Ken Remaining for the game.',
        aiDescription: 'Barbie Ken Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieKenRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieGirl2Remaining: {
    label: 'Barbie Girl 2 Remaining',
    description: 'Uploaded Barbie Girl 2 Remaining for the game.',
    aiDescription: 'a collection of Barbie Girl 2 Remaining for branding',
    items: {
      barbieGirl2Remaining: {
        label: 'Barbie Girl 2 Remaining',
        description: 'The Barbie Girl 2 Remaining for the game.',
        aiDescription: 'Barbie Girl 2 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl2Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoatRemaining: {
        label: 'Barbie Boat Remaining',
        description: 'The Barbie Boat Remaining for the game.',
        aiDescription: 'Barbie Boat Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieBoatRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieCarRemaining: {
        label: 'Barbie Car Remaining',
        description: 'The Barbie Car Remaining for the game.',
        aiDescription: 'Barbie Car Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieCarRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1Remaining: {
        label: 'Barbie Girl 1 Remaining',
        description: 'The Barbie Girl 1 Remaining for the game.',
        aiDescription: 'Barbie Girl 1 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl1Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouseRemaining: {
        label: 'Barbie House Remaining',
        description: 'The Barbie House Remaining for the game.',
        aiDescription: 'Barbie House Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieHouseRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieKenRemaining: {
        label: 'Barbie Ken Remaining',
        description: 'The Barbie Ken Remaining for the game.',
        aiDescription: 'Barbie Ken Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieKenRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieHouseRemaining: {
    label: 'Barbie House Remaining',
    description: 'Uploaded Barbie House Remaining for the game.',
    aiDescription: 'a collection of Barbie House Remaining for branding',
    items: {
      barbieHouseRemaining: {
        label: 'Barbie House Remaining',
        description: 'The Barbie House Remaining for the game.',
        aiDescription: 'Barbie House Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieHouseRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoatRemaining: {
        label: 'Barbie Boat Remaining',
        description: 'The Barbie Boat Remaining for the game.',
        aiDescription: 'Barbie Boat Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieBoatRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieCarRemaining: {
        label: 'Barbie Car Remaining',
        description: 'The Barbie Car Remaining for the game.',
        aiDescription: 'Barbie Car Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieCarRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1Remaining: {
        label: 'Barbie Girl 1 Remaining',
        description: 'The Barbie Girl 1 Remaining for the game.',
        aiDescription: 'Barbie Girl 1 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl1Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2Remaining: {
        label: 'Barbie Girl 2 Remaining',
        description: 'The Barbie Girl 2 Remaining for the game.',
        aiDescription: 'Barbie Girl 2 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl2Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieKenRemaining: {
        label: 'Barbie Ken Remaining',
        description: 'The Barbie Ken Remaining for the game.',
        aiDescription: 'Barbie Ken Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieKenRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieKenRemaining: {
    label: 'Barbie Ken Remaining',
    description: 'Uploaded Barbie Ken Remaining for the game.',
    aiDescription: 'a collection of Barbie Ken Remaining for branding',
    items: {
      barbieKenRemaining: {
        label: 'Barbie Ken Remaining',
        description: 'The Barbie Ken Remaining for the game.',
        aiDescription: 'Barbie Ken Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieKenRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoatRemaining: {
        label: 'Barbie Boat Remaining',
        description: 'The Barbie Boat Remaining for the game.',
        aiDescription: 'Barbie Boat Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieBoatRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieCarRemaining: {
        label: 'Barbie Car Remaining',
        description: 'The Barbie Car Remaining for the game.',
        aiDescription: 'Barbie Car Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieCarRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1Remaining: {
        label: 'Barbie Girl 1 Remaining',
        description: 'The Barbie Girl 1 Remaining for the game.',
        aiDescription: 'Barbie Girl 1 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl1Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2Remaining: {
        label: 'Barbie Girl 2 Remaining',
        description: 'The Barbie Girl 2 Remaining for the game.',
        aiDescription: 'Barbie Girl 2 Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieGirl2Remaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouseRemaining: {
        label: 'Barbie House Remaining',
        description: 'The Barbie House Remaining for the game.',
        aiDescription: 'Barbie House Remaining used in game',
        src: require('./assets/2d/RemainingObj/barbieHouseRemaining.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  nextLevel: {
    label: 'Next Level',
    description: 'Uploaded Next Level for the game.',
    aiDescription: 'a collection of Next Level for branding',
    items: {
      nextLevel: {
        label: 'Next Level',
        description: 'The Next Level for the game.',
        aiDescription: 'Next Level used in game',
        src: require('./assets/audio/nextLevel.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  time: {
    label: 'Time',
    description: 'Uploaded Time for the game.',
    aiDescription: 'a collection of Time for branding',
    items: {
      time: {
        label: 'Time',
        description: 'The Time for the game.',
        aiDescription: 'Time used in game',
        src: require('./assets/audio/time.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  tornado: {
    label: 'Tornado',
    description: 'Uploaded Tornado for the game.',
    aiDescription: 'a collection of Tornado for branding',
    items: {
      tornado: {
        label: 'Tornado',
        description: 'The Tornado for the game.',
        aiDescription: 'Tornado used in game',
        src: require('./assets/audio/tornado.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  magnet: {
    label: 'Magnet',
    description: 'Uploaded Magnet for the game.',
    aiDescription: 'a collection of Magnet for branding',
    items: {
      magnet: {
        label: 'Magnet',
        description: 'The Magnet for the game.',
        aiDescription: 'Magnet used in game',
        src: require('./assets/audio/magnet.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  reverse: {
    label: 'Reverse',
    description: 'Uploaded Reverse for the game.',
    aiDescription: 'a collection of Reverse for branding',
    items: {
      reverse: {
        label: 'Reverse',
        description: 'The Reverse for the game.',
        aiDescription: 'Reverse used in game',
        src: require('./assets/audio/reverse.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  match: {
    label: 'Match',
    description: 'Uploaded Match for the game.',
    aiDescription: 'a collection of Match for branding',
    items: {
      match: {
        label: 'Match',
        description: 'The Match for the game.',
        aiDescription: 'Match used in game',
        src: require('./assets/audio/match.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  click: {
    label: 'Click',
    description: 'Uploaded Click for the game.',
    aiDescription: 'a collection of Click for branding',
    items: {
      click: {
        label: 'Click',
        description: 'The Click for the game.',
        aiDescription: 'Click used in game',
        src: require('./assets/audio/click.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  addTray: {
    label: 'Add Tray',
    description: 'Uploaded Add Tray for the game.',
    aiDescription: 'a collection of Add Tray for branding',
    items: {
      addTray: {
        label: 'Add Tray',
        description: 'The Add Tray for the game.',
        aiDescription: 'Add Tray used in game',
        src: require('./assets/audio/addTray.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  collect: {
    label: 'Collect',
    description: 'Uploaded Collect for the game.',
    aiDescription: 'a collection of Collect for branding',
    items: {
      collect: {
        label: 'Collect',
        description: 'The Collect for the game.',
        aiDescription: 'Collect used in game',
        src: require('./assets/audio/collect.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },

  bgms: {
    label: 'Background Music',
    description: 'Uploaded Background Music for the game.',
    aiDescription: 'a collection of Background Music for branding',
    items: {
      default: {
        label: 'Default',
        description: 'The Background Music for the game.',
        aiDescription: 'Background Music used in game',
        src: require('./assets/audio/bgm.mp3'),
        type: 'audio',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  middleImage: {
    label: 'Middle Image',
    description: 'Uploaded Middle Image for the game.',
    aiDescription: 'a collection of Middle Image for branding',
    items: {
      middleImage: {
        label: 'Middle Image',
        description: 'The Middle Image for the game.',
        aiDescription: 'Middle Image used in game',
        src: require('./assets/2d/endcard/middleImage.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  powerupMagnetGray: {
    label: 'Powerup Magnet Gray',
    description: 'Uploaded Powerup Magnet Gray for the game.',
    aiDescription: 'a collection of Powerup Magnet Gray for branding',
    items: {
      powerupMagnetGray: {
        label: 'Powerup Magnet Gray',
        description: 'The Powerup Magnet Gray for the game.',
        aiDescription: 'Powerup Magnet Gray used in game',
        src: require('./assets/2d/Powerup/powerupMagnetGray.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  powerupReverseGray: {
    label: 'Powerup Reverse Gray',
    description: 'Uploaded Powerup Reverse Gray for the game.',
    aiDescription: 'a collection of Powerup Reverse Gray for branding',
    items: {
      powerupReverseGray: {
        label: 'Powerup Reverse Gray',
        description: 'The Powerup Reverse Gray for the game.',
        aiDescription: 'Powerup Reverse Gray used in game',
        src: require('./assets/2d/Powerup/powerupReverseGray.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  powerupTimeGray: {
    label: 'Powerup Time Gray',
    description: 'Uploaded Powerup Time Gray for the game.',
    aiDescription: 'a collection of Powerup Time Gray for branding',
    items: {
      powerupTimeGray: {
        label: 'Powerup Time Gray',
        description: 'The Powerup Time Gray for the game.',
        aiDescription: 'Powerup Time Gray used in game',
        src: require('./assets/2d/Powerup/powerupTimeGray.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  powerupTornadoGray: {
    label: 'Powerup Tornado Gray',
    description: 'Uploaded Powerup Tornado Gray for the game.',
    aiDescription: 'a collection of Powerup Tornado Gray for branding',
    items: {
      powerupTornadoGray: {
        label: 'Powerup Tornado Gray',
        description: 'The Powerup Tornado Gray for the game.',
        aiDescription: 'Powerup Tornado Gray used in game',
        src: require('./assets/2d/Powerup/powerupTornadoGray.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  endcardButton: {
    label: 'Endcard Button',
    description: 'Uploaded Endcard Button for the game.',
    aiDescription: 'a collection of Endcard Button for branding',
    items: {
      endcardButton: {
        label: 'Endcard Button',
        description: 'The Endcard Button for the game.',
        aiDescription: 'Endcard Button used in game',
        src: require('./assets/2d/endcard/endcardButton.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  endcardLogo: {
    label: 'Endcard Logo',
    description: 'Uploaded Endcard Logo for the game.',
    aiDescription: 'a collection of Endcard Logo for branding',
    items: {
      endcardLogo: {
        label: 'Endcard Logo',
        description: 'The Endcard Logo for the game.',
        aiDescription: 'Endcard Logo used in game',
        src: require('./assets/2d/endcard/endcardLogo.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  hand: {
    label: 'Hand',
    description: 'Uploaded Hand for the game.',
    aiDescription: 'a collection of Hand for branding',
    items: {
      hand: {
        label: 'Hand',
        description: 'The Hand for the game.',
        aiDescription: 'Hand used in game',
        src: require('./assets/2d/hand.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },

  barbieBoat: {
    label: 'Barbie Boat',
    description: 'Uploaded Barbie Boat for the game.',
    aiDescription: 'a collection of Barbie Boat for branding',
    items: {
      barbieBoat: {
        label: 'Barbie Boat',
        description: 'The Barbie Boat for the game.',
        aiDescription: 'Barbie Boat used in game',
        src: require('./assets/models/items/barbie_boat-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieCar: {
        label: 'Barbie Car',
        description: 'The Barbie Car for the game.',
        aiDescription: 'Barbie Car used in game',
        src: require('./assets/models/items/barbie_car-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1: {
        label: 'Barbie Girl 1',
        description: 'The Barbie Girl 1 for the game.',
        aiDescription: 'Barbie Girl 1 used in game',
        src: require('./assets/models/items/barbie_girl1-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2: {
        label: 'Barbie Girl 2',
        description: 'The Barbie Girl 2 for the game.',
        aiDescription: 'Barbie Girl 2 used in game',
        src: require('./assets/models/items/barbie_girl2-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouse: {
        label: 'Barbie House',
        description: 'The Barbie House for the game.',
        aiDescription: 'Barbie House used in game',
        src: require('./assets/models/items/barbie_house-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieKen: {
        label: 'Barbie Ken',
        description: 'The Barbie Ken for the game.',
        aiDescription: 'Barbie Ken used in game',
        src: require('./assets/models/items/barbie_ken-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barney: {
        label: 'Barney',
        description: 'The Barney for the game.',
        aiDescription: 'Barney used in game',
        src: require('./assets/models/items/barney_plush-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      heman: {
        label: 'Heman',
        description: 'The Heman for the game.',
        aiDescription: 'Heman used in game',
        src: require('./assets/models/items/he-man_figurine-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      pingu: {
        label: 'Pingu',
        description: 'The Pingu for the game.',
        aiDescription: 'Pingu used in game',
        src: require('./assets/models/items/pingu_snowboard-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      thomasTrain: {
        label: 'Thomas Train',
        description: 'The Thomas Train for the game.',
        aiDescription: 'Thomas Train used in game',
        src: require('./assets/models/items/thomas_train-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieCar: {
    label: 'Barbie Car',
    description: 'Uploaded Barbie Car for the game.',
    aiDescription: 'a collection of Barbie Car for branding',
    items: {
      barbieCar: {
        label: 'Barbie Car',
        description: 'The Barbie Car for the game.',
        aiDescription: 'Barbie Car used in game',
        src: require('./assets/models/items/barbie_car-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoat: {
        label: 'Barbie Boat',
        description: 'The Barbie Boat for the game.',
        aiDescription: 'Barbie Boat used in game',
        src: require('./assets/models/items/barbie_boat-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1: {
        label: 'Barbie Girl 1',
        description: 'The Barbie Girl 1 for the game.',
        aiDescription: 'Barbie Girl 1 used in game',
        src: require('./assets/models/items/barbie_girl1-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2: {
        label: 'Barbie Girl 2',
        description: 'The Barbie Girl 2 for the game.',
        aiDescription: 'Barbie Girl 2 used in game',
        src: require('./assets/models/items/barbie_girl2-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouse: {
        label: 'Barbie House',
        description: 'The Barbie House for the game.',
        aiDescription: 'Barbie House used in game',
        src: require('./assets/models/items/barbie_house-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieKen: {
        label: 'Barbie Ken',
        description: 'The Barbie Ken for the game.',
        aiDescription: 'Barbie Ken used in game',
        src: require('./assets/models/items/barbie_ken-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barney: {
        label: 'Barney',
        description: 'The Barney for the game.',
        aiDescription: 'Barney used in game',
        src: require('./assets/models/items/barney_plush-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      heman: {
        label: 'Heman',
        description: 'The Heman for the game.',
        aiDescription: 'Heman used in game',
        src: require('./assets/models/items/he-man_figurine-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      pingu: {
        label: 'Pingu',
        description: 'The Pingu for the game.',
        aiDescription: 'Pingu used in game',
        src: require('./assets/models/items/pingu_snowboard-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      thomasTrain: {
        label: 'Thomas Train',
        description: 'The Thomas Train for the game.',
        aiDescription: 'Thomas Train used in game',
        src: require('./assets/models/items/thomas_train-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieGirl1: {
    label: 'Barbie Girl 1',
    description: 'Uploaded Barbie Girl 1 for the game.',
    aiDescription: 'a collection of Barbie Girl 1 for branding',
    items: {
      barbieGirl1: {
        label: 'Barbie Girl 1',
        description: 'The Barbie Girl 1 for the game.',
        aiDescription: 'Barbie Girl 1 used in game',
        src: require('./assets/models/items/barbie_girl1-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoat: {
        label: 'Barbie Boat',
        description: 'The Barbie Boat for the game.',
        aiDescription: 'Barbie Boat used in game',
        src: require('./assets/models/items/barbie_boat-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieCar: {
        label: 'Barbie Car',
        description: 'The Barbie Car for the game.',
        aiDescription: 'Barbie Car used in game',
        src: require('./assets/models/items/barbie_car-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2: {
        label: 'Barbie Girl 2',
        description: 'The Barbie Girl 2 for the game.',
        aiDescription: 'Barbie Girl 2 used in game',
        src: require('./assets/models/items/barbie_girl2-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouse: {
        label: 'Barbie House',
        description: 'The Barbie House for the game.',
        aiDescription: 'Barbie House used in game',
        src: require('./assets/models/items/barbie_house-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieKen: {
        label: 'Barbie Ken',
        description: 'The Barbie Ken for the game.',
        aiDescription: 'Barbie Ken used in game',
        src: require('./assets/models/items/barbie_ken-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barney: {
        label: 'Barney',
        description: 'The Barney for the game.',
        aiDescription: 'Barney used in game',
        src: require('./assets/models/items/barney_plush-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      heman: {
        label: 'Heman',
        description: 'The Heman for the game.',
        aiDescription: 'Heman used in game',
        src: require('./assets/models/items/he-man_figurine-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      pingu: {
        label: 'Pingu',
        description: 'The Pingu for the game.',
        aiDescription: 'Pingu used in game',
        src: require('./assets/models/items/pingu_snowboard-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      thomasTrain: {
        label: 'Thomas Train',
        description: 'The Thomas Train for the game.',
        aiDescription: 'Thomas Train used in game',
        src: require('./assets/models/items/thomas_train-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieGirl2: {
    label: 'Barbie Girl 2',
    description: 'Uploaded Barbie Girl 2 for the game.',
    aiDescription: 'a collection of Barbie Girl 2 for branding',
    items: {
      barbieGirl2: {
        label: 'Barbie Girl 2',
        description: 'The Barbie Girl 2 for the game.',
        aiDescription: 'Barbie Girl 2 used in game',
        src: require('./assets/models/items/barbie_girl2-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoat: {
        label: 'Barbie Boat',
        description: 'The Barbie Boat for the game.',
        aiDescription: 'Barbie Boat used in game',
        src: require('./assets/models/items/barbie_boat-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieCar: {
        label: 'Barbie Car',
        description: 'The Barbie Car for the game.',
        aiDescription: 'Barbie Car used in game',
        src: require('./assets/models/items/barbie_car-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1: {
        label: 'Barbie Girl 1',
        description: 'The Barbie Girl 1 for the game.',
        aiDescription: 'Barbie Girl 1 used in game',
        src: require('./assets/models/items/barbie_girl1-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouse: {
        label: 'Barbie House',
        description: 'The Barbie House for the game.',
        aiDescription: 'Barbie House used in game',
        src: require('./assets/models/items/barbie_house-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieKen: {
        label: 'Barbie Ken',
        description: 'The Barbie Ken for the game.',
        aiDescription: 'Barbie Ken used in game',
        src: require('./assets/models/items/barbie_ken-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barney: {
        label: 'Barney',
        description: 'The Barney for the game.',
        aiDescription: 'Barney used in game',
        src: require('./assets/models/items/barney_plush-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      heman: {
        label: 'Heman',
        description: 'The Heman for the game.',
        aiDescription: 'Heman used in game',
        src: require('./assets/models/items/he-man_figurine-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      pingu: {
        label: 'Pingu',
        description: 'The Pingu for the game.',
        aiDescription: 'Pingu used in game',
        src: require('./assets/models/items/pingu_snowboard-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      thomasTrain: {
        label: 'Thomas Train',
        description: 'The Thomas Train for the game.',
        aiDescription: 'Thomas Train used in game',
        src: require('./assets/models/items/thomas_train-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieHouse: {
    label: 'Barbie House',
    description: 'Uploaded Barbie House for the game.',
    aiDescription: 'a collection of Barbie House for branding',
    items: {
      barbieHouse: {
        label: 'Barbie House',
        description: 'The Barbie House for the game.',
        aiDescription: 'Barbie House used in game',
        src: require('./assets/models/items/barbie_house-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoat: {
        label: 'Barbie Boat',
        description: 'The Barbie Boat for the game.',
        aiDescription: 'Barbie Boat used in game',
        src: require('./assets/models/items/barbie_boat-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieCar: {
        label: 'Barbie Car',
        description: 'The Barbie Car for the game.',
        aiDescription: 'Barbie Car used in game',
        src: require('./assets/models/items/barbie_car-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1: {
        label: 'Barbie Girl 1',
        description: 'The Barbie Girl 1 for the game.',
        aiDescription: 'Barbie Girl 1 used in game',
        src: require('./assets/models/items/barbie_girl1-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2: {
        label: 'Barbie Girl 2',
        description: 'The Barbie Girl 2 for the game.',
        aiDescription: 'Barbie Girl 2 used in game',
        src: require('./assets/models/items/barbie_girl2-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieKen: {
        label: 'Barbie Ken',
        description: 'The Barbie Ken for the game.',
        aiDescription: 'Barbie Ken used in game',
        src: require('./assets/models/items/barbie_ken-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barney: {
        label: 'Barney',
        description: 'The Barney for the game.',
        aiDescription: 'Barney used in game',
        src: require('./assets/models/items/barney_plush-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      heman: {
        label: 'Heman',
        description: 'The Heman for the game.',
        aiDescription: 'Heman used in game',
        src: require('./assets/models/items/he-man_figurine-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      pingu: {
        label: 'Pingu',
        description: 'The Pingu for the game.',
        aiDescription: 'Pingu used in game',
        src: require('./assets/models/items/pingu_snowboard-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      thomasTrain: {
        label: 'Thomas Train',
        description: 'The Thomas Train for the game.',
        aiDescription: 'Thomas Train used in game',
        src: require('./assets/models/items/thomas_train-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  barbieKen: {
    label: 'Barbie Ken',
    description: 'Uploaded Barbie Ken for the game.',
    aiDescription: 'a collection of Barbie Ken for branding',
    items: {
      barbieKen: {
        label: 'Barbie Ken',
        description: 'The Barbie Ken for the game.',
        aiDescription: 'Barbie Ken used in game',
        src: require('./assets/models/items/barbie_ken-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieBoat: {
        label: 'Barbie Boat',
        description: 'The Barbie Boat for the game.',
        aiDescription: 'Barbie Boat used in game',
        src: require('./assets/models/items/barbie_boat-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieCar: {
        label: 'Barbie Car',
        description: 'The Barbie Car for the game.',
        aiDescription: 'Barbie Car used in game',
        src: require('./assets/models/items/barbie_car-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl1: {
        label: 'Barbie Girl 1',
        description: 'The Barbie Girl 1 for the game.',
        aiDescription: 'Barbie Girl 1 used in game',
        src: require('./assets/models/items/barbie_girl1-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieGirl2: {
        label: 'Barbie Girl 2',
        description: 'The Barbie Girl 2 for the game.',
        aiDescription: 'Barbie Girl 2 used in game',
        src: require('./assets/models/items/barbie_girl2-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barbieHouse: {
        label: 'Barbie House',
        description: 'The Barbie House for the game.',
        aiDescription: 'Barbie House used in game',
        src: require('./assets/models/items/barbie_house-v2.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      barney: {
        label: 'Barney',
        description: 'The Barney for the game.',
        aiDescription: 'Barney used in game',
        src: require('./assets/models/items/barney_plush-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      heman: {
        label: 'Heman',
        description: 'The Heman for the game.',
        aiDescription: 'Heman used in game',
        src: require('./assets/models/items/he-man_figurine-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      pingu: {
        label: 'Pingu',
        description: 'The Pingu for the game.',
        aiDescription: 'Pingu used in game',
        src: require('./assets/models/items/pingu_snowboard-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
      thomasTrain: {
        label: 'Thomas Train',
        description: 'The Thomas Train for the game.',
        aiDescription: 'Thomas Train used in game',
        src: require('./assets/models/items/thomas_train-v1.glb'),
        type: 'glb',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  powerupMagnet: {
    label: 'Powerup Magnet',
    description: 'Uploaded Powerup Magnet for the game.',
    aiDescription: 'a collection of Powerup Magnet for branding',
    items: {
      powerupMagnet: {
        label: 'Powerup Magnet',
        description: 'The Powerup Magnet for the game.',
        aiDescription: 'Powerup Magnet used in game',
        src: require('./assets/2d/Powerup/powerupMagnet.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  powerupReverse: {
    label: 'Powerup Reverse',
    description: 'Uploaded Powerup Reverse for the game.',
    aiDescription: 'a collection of Powerup Reverse for branding',
    items: {
      powerupReverse: {
        label: 'Powerup Reverse',
        description: 'The Powerup Reverse for the game.',
        aiDescription: 'Powerup Reverse used in game',
        src: require('./assets/2d/Powerup/powerupReverse.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  powerupTime: {
    label: 'Powerup Time',
    description: 'Uploaded Powerup Time for the game.',
    aiDescription: 'a collection of Powerup Time for branding',
    items: {
      powerupTime: {
        label: 'Powerup Time',
        description: 'The Powerup Time for the game.',
        aiDescription: 'Powerup Time used in game',
        src: require('./assets/2d/Powerup/powerupTime.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
  powerupTornado: {
    label: 'Powerup Tornado',
    description: 'Uploaded Powerup Tornado for the game.',
    aiDescription: 'a collection of Powerup Tornado for branding',
    items: {
      powerupTornado: {
        label: 'Powerup Tornado',
        description: 'The Powerup Tornado for the game.',
        aiDescription: 'Powerup Tornado used in game',
        src: require('./assets/2d/Powerup/powerupTornado.png'),
        type: 'image',
        previewIcon: 'base64-preview-primary',
      },
    },
  },
};

module.exports = { collectStorage, storage };
